version: '3'
services:
    web:
        build:
            context: .
            dockerfile: nginx/Dockerfile
        ports:
            - "8000:80"
        restart: always
        volumes:
            - "./nginx/default.conf:/etc/nginx/conf.d/default.conf"
#            - "./public:/var/www/public/"
        depends_on:
            - php
#            - mysql
    php:
        build:
            context: .
            dockerfile: php/Dockerfile
        restart: always
#        volumes:
#            - "./public:/var/www/public"
#        links:
#            - mysql
#    mysql:
#      image: mysql
 #     ports:
#        - "3306:3306"
#      environment:
#        - MYSQL_ROOT_PASSWORD=123456
#        - MYSQL_DATABASE=docker_test
#      volumes:
#        - ./etc/mysql:/docker-entrypoint-initdb.d
