version: '3'
services:
    web:
        image: nginx:latest
        ports:
            - "8000:80"
        restart: always
        volumes:
            - "./nginx/default.conf:/etc/nginx/conf.d/default.conf"
            - "./public:/var/www/html"
        depends_on:
            - php
            - db
    php:
        image: nanoninja/php-fpm
        restart: always
        volumes:
            - "./public:/var/www/html"
    db:
        image: mysql
        ports:
          - "3000"
        environment:
          MYSQL_ROOT_PASSWORD: "123456"
          MYSQL_DATABASE: "landth1103"
        volumes:
            - ./mysql/db:/docker-entrypoint-initdb.d
#    db:
#        image: wnameless/oracle-xe-11g
#        ports:
#            - "3000"
