FROM nginx:latest



#RUN mkdir /var/www
#RUN mkdir /var/www/html
#RUN cd /var/www/html
#RUN git clone https://github.com/lando110390/yii2_basic.git

#ADD run.sh /usr/local/bin/run.sh
#RUN chmod +x /usr/local/bin/run.sh
#CMD ["/usr/local/bin/run.sh"]

#CMD ["echo", "MY_HOME"]